// GENERATED by scripts/i18n/scaffold.mjs from scripts/i18n/namespaces.json — do not edit by hand.
// To add a namespace: add it to namespaces.json and run `node scripts/i18n/scaffold.mjs`.

import { DEFAULT_UI_LOCALE, mergeMessages, type UiLocale } from '@favornoms/shared';
import en_nav from '../../messages/en/nav.json';
import en_common from '../../messages/en/common.json';
import en_login from '../../messages/en/login.json';
import en_shell from '../../messages/en/shell.json';
import en_install from '../../messages/en/install.json';
import en_home from '../../messages/en/home.json';
import en_dispatch from '../../messages/en/dispatch.json';
import en_active from '../../messages/en/active.json';
import en_onboarding from '../../messages/en/onboarding.json';
import en_profile from '../../messages/en/profile.json';
import en_history from '../../messages/en/history.json';
import en_coverage from '../../messages/en/coverage.json';
import en_earnings from '../../messages/en/earnings.json';
import en_errors from '../../messages/en/errors.json';
import es_nav from '../../messages/es/nav.json';
import es_common from '../../messages/es/common.json';
import es_login from '../../messages/es/login.json';
import es_shell from '../../messages/es/shell.json';
import es_install from '../../messages/es/install.json';
import es_home from '../../messages/es/home.json';
import es_dispatch from '../../messages/es/dispatch.json';
import es_active from '../../messages/es/active.json';
import es_onboarding from '../../messages/es/onboarding.json';
import es_profile from '../../messages/es/profile.json';
import es_history from '../../messages/es/history.json';
import es_coverage from '../../messages/es/coverage.json';
import es_earnings from '../../messages/es/earnings.json';
import es_errors from '../../messages/es/errors.json';
import vi_nav from '../../messages/vi/nav.json';
import vi_common from '../../messages/vi/common.json';
import vi_login from '../../messages/vi/login.json';
import vi_shell from '../../messages/vi/shell.json';
import vi_install from '../../messages/vi/install.json';
import vi_home from '../../messages/vi/home.json';
import vi_dispatch from '../../messages/vi/dispatch.json';
import vi_active from '../../messages/vi/active.json';
import vi_onboarding from '../../messages/vi/onboarding.json';
import vi_profile from '../../messages/vi/profile.json';
import vi_history from '../../messages/vi/history.json';
import vi_coverage from '../../messages/vi/coverage.json';
import vi_earnings from '../../messages/vi/earnings.json';
import vi_errors from '../../messages/vi/errors.json';
import th_nav from '../../messages/th/nav.json';
import th_common from '../../messages/th/common.json';
import th_login from '../../messages/th/login.json';
import th_shell from '../../messages/th/shell.json';
import th_install from '../../messages/th/install.json';
import th_home from '../../messages/th/home.json';
import th_dispatch from '../../messages/th/dispatch.json';
import th_active from '../../messages/th/active.json';
import th_onboarding from '../../messages/th/onboarding.json';
import th_profile from '../../messages/th/profile.json';
import th_history from '../../messages/th/history.json';
import th_coverage from '../../messages/th/coverage.json';
import th_earnings from '../../messages/th/earnings.json';
import th_errors from '../../messages/th/errors.json';

type MessageTree = { [key: string]: string | MessageTree };

const CATALOG: Record<UiLocale, MessageTree> = {
  en: {
    nav: en_nav,
    common: en_common,
    login: en_login,
    shell: en_shell,
    install: en_install,
    home: en_home,
    dispatch: en_dispatch,
    active: en_active,
    onboarding: en_onboarding,
    profile: en_profile,
    history: en_history,
    coverage: en_coverage,
    earnings: en_earnings,
    errors: en_errors,
  },
  es: {
    nav: es_nav,
    common: es_common,
    login: es_login,
    shell: es_shell,
    install: es_install,
    home: es_home,
    dispatch: es_dispatch,
    active: es_active,
    onboarding: es_onboarding,
    profile: es_profile,
    history: es_history,
    coverage: es_coverage,
    earnings: es_earnings,
    errors: es_errors,
  },
  vi: {
    nav: vi_nav,
    common: vi_common,
    login: vi_login,
    shell: vi_shell,
    install: vi_install,
    home: vi_home,
    dispatch: vi_dispatch,
    active: vi_active,
    onboarding: vi_onboarding,
    profile: vi_profile,
    history: vi_history,
    coverage: vi_coverage,
    earnings: vi_earnings,
    errors: vi_errors,
  },
  th: {
    nav: th_nav,
    common: th_common,
    login: th_login,
    shell: th_shell,
    install: th_install,
    home: th_home,
    dispatch: th_dispatch,
    active: th_active,
    onboarding: th_onboarding,
    profile: th_profile,
    history: th_history,
    coverage: th_coverage,
    earnings: th_earnings,
    errors: th_errors,
  },
} as unknown as Record<UiLocale, MessageTree>;

export const NAMESPACES = ["nav","common","login","shell","install","home","dispatch","active","onboarding","profile","history","coverage","earnings","errors"] as const;

/** The messages for a language, with English underneath: a key not yet translated shows English,
 *  never a raw key path. */
export function messagesFor(locale: UiLocale): MessageTree {
  const english = CATALOG[DEFAULT_UI_LOCALE];
  return locale === DEFAULT_UI_LOCALE ? english : mergeMessages(english, CATALOG[locale]);
}
