#!/usr/bin/env node
// Creates the per-namespace message files and regenerates each app's static message loader.
//
//   node scripts/i18n/scaffold.mjs
//
// Namespaces are listed in scripts/i18n/namespaces.json. Existing message files are never
// overwritten; a legacy apps/<app>/messages/en.json is split into en/<namespace>.json once and
// then removed. The loader (apps/<app>/src/i18n/messages.ts) is imported statically so every
// language ships with the server bundle — a dynamic path would be missed by output tracing.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const LOCALES = ['en', 'es', 'vi', 'th'];
const NAMESPACES = JSON.parse(fs.readFileSync(path.join(ROOT, 'scripts/i18n/namespaces.json'), 'utf8'));

const ident = (s) => s.replace(/[^A-Za-z0-9]/g, '_');

for (const [app, namespaces] of Object.entries(NAMESPACES)) {
  const messagesDir = path.join(ROOT, 'apps', app, 'messages');
  const legacyPath = path.join(messagesDir, 'en.json');
  const legacy = fs.existsSync(legacyPath) ? JSON.parse(fs.readFileSync(legacyPath, 'utf8')) : null;

  for (const locale of LOCALES) {
    const dir = path.join(messagesDir, locale);
    fs.mkdirSync(dir, { recursive: true });
    for (const ns of namespaces) {
      const file = path.join(dir, `${ns}.json`);
      if (fs.existsSync(file)) continue;
      const seed = locale === 'en' && legacy && legacy[ns] && typeof legacy[ns] === 'object' ? legacy[ns] : {};
      fs.writeFileSync(file, `${JSON.stringify(seed, null, 2)}\n`);
    }
  }
  if (legacy) {
    const dropped = Object.keys(legacy).filter((k) => !namespaces.includes(k));
    if (dropped.length) console.log(`${app}: legacy keys not carried over (unused namespaces): ${dropped.join(', ')}`);
    fs.unlinkSync(legacyPath);
  }

  const imports = [];
  const catalog = [];
  for (const locale of LOCALES) {
    const entries = [];
    for (const ns of namespaces) {
      const name = `${locale}_${ident(ns)}`;
      imports.push(`import ${name} from '../../messages/${locale}/${ns}.json';`);
      entries.push(`    ${ns}: ${name},`);
    }
    catalog.push(`  ${locale}: {\n${entries.join('\n')}\n  },`);
  }

  const loader = `// GENERATED by scripts/i18n/scaffold.mjs from scripts/i18n/namespaces.json — do not edit by hand.
// To add a namespace: add it to namespaces.json and run \`node scripts/i18n/scaffold.mjs\`.

import { DEFAULT_UI_LOCALE, mergeMessages, type UiLocale } from '@favornoms/shared';
${imports.join('\n')}

type MessageTree = { [key: string]: string | MessageTree };

const CATALOG: Record<UiLocale, MessageTree> = {
${catalog.join('\n')}
} as unknown as Record<UiLocale, MessageTree>;

export const NAMESPACES = ${JSON.stringify(namespaces)} as const;

/** The messages for a language, with English underneath: a key not yet translated shows English,
 *  never a raw key path. */
export function messagesFor(locale: UiLocale): MessageTree {
  const english = CATALOG[DEFAULT_UI_LOCALE];
  return locale === DEFAULT_UI_LOCALE ? english : mergeMessages(english, CATALOG[locale]);
}
`;
  fs.writeFileSync(path.join(ROOT, 'apps', app, 'src/i18n/messages.ts'), loader);
  console.log(`${app}: ${namespaces.length} namespaces x ${LOCALES.length} languages, loader written`);
}
