// GENERATED by scripts/i18n/scaffold.mjs from scripts/i18n/namespaces.json — do not edit by hand.
// To add a namespace: add it to namespaces.json and run `node scripts/i18n/scaffold.mjs`.

import { DEFAULT_UI_LOCALE, mergeMessages, type UiLocale } from '@favornoms/shared';
import en_common from '../../messages/en/common.json';
import en_shell from '../../messages/en/shell.json';
import en_auth from '../../messages/en/auth.json';
import en_onboarding from '../../messages/en/onboarding.json';
import en_invite from '../../messages/en/invite.json';
import en_kitchen from '../../messages/en/kitchen.json';
import en_counter from '../../messages/en/counter.json';
import en_dashboard from '../../messages/en/dashboard.json';
import en_orders from '../../messages/en/orders.json';
import en_deliveries from '../../messages/en/deliveries.json';
import en_menu from '../../messages/en/menu.json';
import en_branch from '../../messages/en/branch.json';
import en_settings from '../../messages/en/settings.json';
import en_loyalty from '../../messages/en/loyalty.json';
import en_reports from '../../messages/en/reports.json';
import en_staff from '../../messages/en/staff.json';
import en_payouts from '../../messages/en/payouts.json';
import en_customers from '../../messages/en/customers.json';
import en_hq from '../../messages/en/hq.json';
import en_platform from '../../messages/en/platform.json';
import en_errors from '../../messages/en/errors.json';
import en_menuExtras from '../../messages/en/menuExtras.json';
import en_inventory from '../../messages/en/inventory.json';
import en_branchOps from '../../messages/en/branchOps.json';
import en_brands from '../../messages/en/brands.json';
import en_qr from '../../messages/en/qr.json';
import en_tables from '../../messages/en/tables.json';
import en_promos from '../../messages/en/promos.json';
import en_ratings from '../../messages/en/ratings.json';
import en_drivers from '../../messages/en/drivers.json';
import en_misc from '../../messages/en/misc.json';
import en_platformBilling from '../../messages/en/platformBilling.json';
import es_common from '../../messages/es/common.json';
import es_shell from '../../messages/es/shell.json';
import es_auth from '../../messages/es/auth.json';
import es_onboarding from '../../messages/es/onboarding.json';
import es_invite from '../../messages/es/invite.json';
import es_kitchen from '../../messages/es/kitchen.json';
import es_counter from '../../messages/es/counter.json';
import es_dashboard from '../../messages/es/dashboard.json';
import es_orders from '../../messages/es/orders.json';
import es_deliveries from '../../messages/es/deliveries.json';
import es_menu from '../../messages/es/menu.json';
import es_branch from '../../messages/es/branch.json';
import es_settings from '../../messages/es/settings.json';
import es_loyalty from '../../messages/es/loyalty.json';
import es_reports from '../../messages/es/reports.json';
import es_staff from '../../messages/es/staff.json';
import es_payouts from '../../messages/es/payouts.json';
import es_customers from '../../messages/es/customers.json';
import es_hq from '../../messages/es/hq.json';
import es_platform from '../../messages/es/platform.json';
import es_errors from '../../messages/es/errors.json';
import es_menuExtras from '../../messages/es/menuExtras.json';
import es_inventory from '../../messages/es/inventory.json';
import es_branchOps from '../../messages/es/branchOps.json';
import es_brands from '../../messages/es/brands.json';
import es_qr from '../../messages/es/qr.json';
import es_tables from '../../messages/es/tables.json';
import es_promos from '../../messages/es/promos.json';
import es_ratings from '../../messages/es/ratings.json';
import es_drivers from '../../messages/es/drivers.json';
import es_misc from '../../messages/es/misc.json';
import es_platformBilling from '../../messages/es/platformBilling.json';
import vi_common from '../../messages/vi/common.json';
import vi_shell from '../../messages/vi/shell.json';
import vi_auth from '../../messages/vi/auth.json';
import vi_onboarding from '../../messages/vi/onboarding.json';
import vi_invite from '../../messages/vi/invite.json';
import vi_kitchen from '../../messages/vi/kitchen.json';
import vi_counter from '../../messages/vi/counter.json';
import vi_dashboard from '../../messages/vi/dashboard.json';
import vi_orders from '../../messages/vi/orders.json';
import vi_deliveries from '../../messages/vi/deliveries.json';
import vi_menu from '../../messages/vi/menu.json';
import vi_branch from '../../messages/vi/branch.json';
import vi_settings from '../../messages/vi/settings.json';
import vi_loyalty from '../../messages/vi/loyalty.json';
import vi_reports from '../../messages/vi/reports.json';
import vi_staff from '../../messages/vi/staff.json';
import vi_payouts from '../../messages/vi/payouts.json';
import vi_customers from '../../messages/vi/customers.json';
import vi_hq from '../../messages/vi/hq.json';
import vi_platform from '../../messages/vi/platform.json';
import vi_errors from '../../messages/vi/errors.json';
import vi_menuExtras from '../../messages/vi/menuExtras.json';
import vi_inventory from '../../messages/vi/inventory.json';
import vi_branchOps from '../../messages/vi/branchOps.json';
import vi_brands from '../../messages/vi/brands.json';
import vi_qr from '../../messages/vi/qr.json';
import vi_tables from '../../messages/vi/tables.json';
import vi_promos from '../../messages/vi/promos.json';
import vi_ratings from '../../messages/vi/ratings.json';
import vi_drivers from '../../messages/vi/drivers.json';
import vi_misc from '../../messages/vi/misc.json';
import vi_platformBilling from '../../messages/vi/platformBilling.json';
import th_common from '../../messages/th/common.json';
import th_shell from '../../messages/th/shell.json';
import th_auth from '../../messages/th/auth.json';
import th_onboarding from '../../messages/th/onboarding.json';
import th_invite from '../../messages/th/invite.json';
import th_kitchen from '../../messages/th/kitchen.json';
import th_counter from '../../messages/th/counter.json';
import th_dashboard from '../../messages/th/dashboard.json';
import th_orders from '../../messages/th/orders.json';
import th_deliveries from '../../messages/th/deliveries.json';
import th_menu from '../../messages/th/menu.json';
import th_branch from '../../messages/th/branch.json';
import th_settings from '../../messages/th/settings.json';
import th_loyalty from '../../messages/th/loyalty.json';
import th_reports from '../../messages/th/reports.json';
import th_staff from '../../messages/th/staff.json';
import th_payouts from '../../messages/th/payouts.json';
import th_customers from '../../messages/th/customers.json';
import th_hq from '../../messages/th/hq.json';
import th_platform from '../../messages/th/platform.json';
import th_errors from '../../messages/th/errors.json';
import th_menuExtras from '../../messages/th/menuExtras.json';
import th_inventory from '../../messages/th/inventory.json';
import th_branchOps from '../../messages/th/branchOps.json';
import th_brands from '../../messages/th/brands.json';
import th_qr from '../../messages/th/qr.json';
import th_tables from '../../messages/th/tables.json';
import th_promos from '../../messages/th/promos.json';
import th_ratings from '../../messages/th/ratings.json';
import th_drivers from '../../messages/th/drivers.json';
import th_misc from '../../messages/th/misc.json';
import th_platformBilling from '../../messages/th/platformBilling.json';

type MessageTree = { [key: string]: string | MessageTree };

const CATALOG: Record<UiLocale, MessageTree> = {
  en: {
    common: en_common,
    shell: en_shell,
    auth: en_auth,
    onboarding: en_onboarding,
    invite: en_invite,
    kitchen: en_kitchen,
    counter: en_counter,
    dashboard: en_dashboard,
    orders: en_orders,
    deliveries: en_deliveries,
    menu: en_menu,
    branch: en_branch,
    settings: en_settings,
    loyalty: en_loyalty,
    reports: en_reports,
    staff: en_staff,
    payouts: en_payouts,
    customers: en_customers,
    hq: en_hq,
    platform: en_platform,
    errors: en_errors,
    menuExtras: en_menuExtras,
    inventory: en_inventory,
    branchOps: en_branchOps,
    brands: en_brands,
    qr: en_qr,
    tables: en_tables,
    promos: en_promos,
    ratings: en_ratings,
    drivers: en_drivers,
    misc: en_misc,
    platformBilling: en_platformBilling,
  },
  es: {
    common: es_common,
    shell: es_shell,
    auth: es_auth,
    onboarding: es_onboarding,
    invite: es_invite,
    kitchen: es_kitchen,
    counter: es_counter,
    dashboard: es_dashboard,
    orders: es_orders,
    deliveries: es_deliveries,
    menu: es_menu,
    branch: es_branch,
    settings: es_settings,
    loyalty: es_loyalty,
    reports: es_reports,
    staff: es_staff,
    payouts: es_payouts,
    customers: es_customers,
    hq: es_hq,
    platform: es_platform,
    errors: es_errors,
    menuExtras: es_menuExtras,
    inventory: es_inventory,
    branchOps: es_branchOps,
    brands: es_brands,
    qr: es_qr,
    tables: es_tables,
    promos: es_promos,
    ratings: es_ratings,
    drivers: es_drivers,
    misc: es_misc,
    platformBilling: es_platformBilling,
  },
  vi: {
    common: vi_common,
    shell: vi_shell,
    auth: vi_auth,
    onboarding: vi_onboarding,
    invite: vi_invite,
    kitchen: vi_kitchen,
    counter: vi_counter,
    dashboard: vi_dashboard,
    orders: vi_orders,
    deliveries: vi_deliveries,
    menu: vi_menu,
    branch: vi_branch,
    settings: vi_settings,
    loyalty: vi_loyalty,
    reports: vi_reports,
    staff: vi_staff,
    payouts: vi_payouts,
    customers: vi_customers,
    hq: vi_hq,
    platform: vi_platform,
    errors: vi_errors,
    menuExtras: vi_menuExtras,
    inventory: vi_inventory,
    branchOps: vi_branchOps,
    brands: vi_brands,
    qr: vi_qr,
    tables: vi_tables,
    promos: vi_promos,
    ratings: vi_ratings,
    drivers: vi_drivers,
    misc: vi_misc,
    platformBilling: vi_platformBilling,
  },
  th: {
    common: th_common,
    shell: th_shell,
    auth: th_auth,
    onboarding: th_onboarding,
    invite: th_invite,
    kitchen: th_kitchen,
    counter: th_counter,
    dashboard: th_dashboard,
    orders: th_orders,
    deliveries: th_deliveries,
    menu: th_menu,
    branch: th_branch,
    settings: th_settings,
    loyalty: th_loyalty,
    reports: th_reports,
    staff: th_staff,
    payouts: th_payouts,
    customers: th_customers,
    hq: th_hq,
    platform: th_platform,
    errors: th_errors,
    menuExtras: th_menuExtras,
    inventory: th_inventory,
    branchOps: th_branchOps,
    brands: th_brands,
    qr: th_qr,
    tables: th_tables,
    promos: th_promos,
    ratings: th_ratings,
    drivers: th_drivers,
    misc: th_misc,
    platformBilling: th_platformBilling,
  },
} as unknown as Record<UiLocale, MessageTree>;

export const NAMESPACES = ["common","shell","auth","onboarding","invite","kitchen","counter","dashboard","orders","deliveries","menu","branch","settings","loyalty","reports","staff","payouts","customers","hq","platform","errors","menuExtras","inventory","branchOps","brands","qr","tables","promos","ratings","drivers","misc","platformBilling"] as const;

/** The messages for a language, with English underneath: a key not yet translated shows English,
 *  never a raw key path. */
export function messagesFor(locale: UiLocale): MessageTree {
  const english = CATALOG[DEFAULT_UI_LOCALE];
  return locale === DEFAULT_UI_LOCALE ? english : mergeMessages(english, CATALOG[locale]);
}
