// GENERATED by scripts/i18n/scaffold.mjs from scripts/i18n/namespaces.json — do not edit by hand.
// To add a namespace: add it to namespaces.json and run `node scripts/i18n/scaffold.mjs`.

import { DEFAULT_UI_LOCALE, mergeMessages, type UiLocale } from '@favornoms/shared';
import en_nav from '../../messages/en/nav.json';
import en_channel from '../../messages/en/channel.json';
import en_orderType from '../../messages/en/orderType.json';
import en_common from '../../messages/en/common.json';
import en_storefront from '../../messages/en/storefront.json';
import en_menu from '../../messages/en/menu.json';
import en_cart from '../../messages/en/cart.json';
import en_checkout from '../../messages/en/checkout.json';
import en_tracking from '../../messages/en/tracking.json';
import en_orders from '../../messages/en/orders.json';
import en_account from '../../messages/en/account.json';
import en_loyalty from '../../messages/en/loyalty.json';
import en_auth from '../../messages/en/auth.json';
import en_table from '../../messages/en/table.json';
import en_help from '../../messages/en/help.json';
import en_landing from '../../messages/en/landing.json';
import en_errors from '../../messages/en/errors.json';
import es_nav from '../../messages/es/nav.json';
import es_channel from '../../messages/es/channel.json';
import es_orderType from '../../messages/es/orderType.json';
import es_common from '../../messages/es/common.json';
import es_storefront from '../../messages/es/storefront.json';
import es_menu from '../../messages/es/menu.json';
import es_cart from '../../messages/es/cart.json';
import es_checkout from '../../messages/es/checkout.json';
import es_tracking from '../../messages/es/tracking.json';
import es_orders from '../../messages/es/orders.json';
import es_account from '../../messages/es/account.json';
import es_loyalty from '../../messages/es/loyalty.json';
import es_auth from '../../messages/es/auth.json';
import es_table from '../../messages/es/table.json';
import es_help from '../../messages/es/help.json';
import es_landing from '../../messages/es/landing.json';
import es_errors from '../../messages/es/errors.json';
import vi_nav from '../../messages/vi/nav.json';
import vi_channel from '../../messages/vi/channel.json';
import vi_orderType from '../../messages/vi/orderType.json';
import vi_common from '../../messages/vi/common.json';
import vi_storefront from '../../messages/vi/storefront.json';
import vi_menu from '../../messages/vi/menu.json';
import vi_cart from '../../messages/vi/cart.json';
import vi_checkout from '../../messages/vi/checkout.json';
import vi_tracking from '../../messages/vi/tracking.json';
import vi_orders from '../../messages/vi/orders.json';
import vi_account from '../../messages/vi/account.json';
import vi_loyalty from '../../messages/vi/loyalty.json';
import vi_auth from '../../messages/vi/auth.json';
import vi_table from '../../messages/vi/table.json';
import vi_help from '../../messages/vi/help.json';
import vi_landing from '../../messages/vi/landing.json';
import vi_errors from '../../messages/vi/errors.json';
import th_nav from '../../messages/th/nav.json';
import th_channel from '../../messages/th/channel.json';
import th_orderType from '../../messages/th/orderType.json';
import th_common from '../../messages/th/common.json';
import th_storefront from '../../messages/th/storefront.json';
import th_menu from '../../messages/th/menu.json';
import th_cart from '../../messages/th/cart.json';
import th_checkout from '../../messages/th/checkout.json';
import th_tracking from '../../messages/th/tracking.json';
import th_orders from '../../messages/th/orders.json';
import th_account from '../../messages/th/account.json';
import th_loyalty from '../../messages/th/loyalty.json';
import th_auth from '../../messages/th/auth.json';
import th_table from '../../messages/th/table.json';
import th_help from '../../messages/th/help.json';
import th_landing from '../../messages/th/landing.json';
import th_errors from '../../messages/th/errors.json';

type MessageTree = { [key: string]: string | MessageTree };

const CATALOG: Record<UiLocale, MessageTree> = {
  en: {
    nav: en_nav,
    channel: en_channel,
    orderType: en_orderType,
    common: en_common,
    storefront: en_storefront,
    menu: en_menu,
    cart: en_cart,
    checkout: en_checkout,
    tracking: en_tracking,
    orders: en_orders,
    account: en_account,
    loyalty: en_loyalty,
    auth: en_auth,
    table: en_table,
    help: en_help,
    landing: en_landing,
    errors: en_errors,
  },
  es: {
    nav: es_nav,
    channel: es_channel,
    orderType: es_orderType,
    common: es_common,
    storefront: es_storefront,
    menu: es_menu,
    cart: es_cart,
    checkout: es_checkout,
    tracking: es_tracking,
    orders: es_orders,
    account: es_account,
    loyalty: es_loyalty,
    auth: es_auth,
    table: es_table,
    help: es_help,
    landing: es_landing,
    errors: es_errors,
  },
  vi: {
    nav: vi_nav,
    channel: vi_channel,
    orderType: vi_orderType,
    common: vi_common,
    storefront: vi_storefront,
    menu: vi_menu,
    cart: vi_cart,
    checkout: vi_checkout,
    tracking: vi_tracking,
    orders: vi_orders,
    account: vi_account,
    loyalty: vi_loyalty,
    auth: vi_auth,
    table: vi_table,
    help: vi_help,
    landing: vi_landing,
    errors: vi_errors,
  },
  th: {
    nav: th_nav,
    channel: th_channel,
    orderType: th_orderType,
    common: th_common,
    storefront: th_storefront,
    menu: th_menu,
    cart: th_cart,
    checkout: th_checkout,
    tracking: th_tracking,
    orders: th_orders,
    account: th_account,
    loyalty: th_loyalty,
    auth: th_auth,
    table: th_table,
    help: th_help,
    landing: th_landing,
    errors: th_errors,
  },
} as unknown as Record<UiLocale, MessageTree>;

export const NAMESPACES = ["nav","channel","orderType","common","storefront","menu","cart","checkout","tracking","orders","account","loyalty","auth","table","help","landing","errors"] as const;

/** The messages for a language, with English underneath: a key not yet translated shows English,
 *  never a raw key path. */
export function messagesFor(locale: UiLocale): MessageTree {
  const english = CATALOG[DEFAULT_UI_LOCALE];
  return locale === DEFAULT_UI_LOCALE ? english : mergeMessages(english, CATALOG[locale]);
}
